#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

define('YII_DEBUG', true);
define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = require(__DIR__ . '/config/app/console.php');
if(file_exists(__DIR__ . '/config/app/console.local.php')) {
    $config = \yii\helpers\ArrayHelper::merge($config, include __DIR__ . '/config/app/console.local.php');
}
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
